### ISSUE TITLE
exercice sql

### ISSUE THREAD

**Issue by SylvainTorrenti** [SylvainTorrenti/DWWM_2005#4]
pouvez me dire si les 3 premier énoncer son juste?
merci.

https://github.com/arfpchatelot/MERISE-/blob/master/SQL_ldd_tp.pdf
https://github.com/arfpchatelot/MERISE-/blob/master/EXO_modele_relationnel_20_05.docx

**Comment by mdevoldere** [comment]
Top :)

**Comment by SylvainTorrenti** [comment]
Merci
